### ISSUE TITLE
I can't install drawnow package on anaconda environment.

### ISSUE THREAD

**Issue by sripetta** [stsievert/python-drawnow#4]
Problem Description

I need to install drawnow package.
I tried to use Anaconda Navigator and the package don't exist.
Then, I tried to use Anaconda console:

```
conda install drawone
PackageNotFoundError: Packages missing in current channels:

drawnow
We have searched for the packages in the following channels:

https://repo.continuum.io/pkgs/main/win-64
https://repo.continuum.io/pkgs/main/noarch
https://repo.continuum.io/pkgs/free/win-64
https://repo.continuum.io/pkgs/free/noarch
https://repo.continuum.io/pkgs/r/win-64
https://repo.continuum.io/pkgs/r/noarch
https://repo.continuum.io/pkgs/pro/win-64
https://repo.continuum.io/pkgs/pro/noarch
https://repo.continuum.io/pkgs/msys2/win-64
https://repo.continuum.io/pkgs/msys2/noarch
pip install drawnow
Exception:
Traceback (most recent call last):
File "C:\ProgramData\Anaconda2\lib\site-packages\pip\basecommand.py", line 215
, in main
status = self.run(options, args)
File "C:\ProgramData\Anaconda2\lib\site-packages\pip\commands\install.py", lin
e 335, in run
wb.build(autobuilding=True)
File "C:\ProgramData\Anaconda2\lib\site-packages\pip\wheel.py", line 749, in b
uild
self.requirement_set.prepare_files(self.finder)
File "C:\ProgramData\Anaconda2\lib\site-packages\pip\req\req_set.py", line 380
, in prepare_files
ignore_dependencies=self.ignore_dependencies))
File "C:\ProgramData\Anaconda2\lib\site-packages\pip\req\req_set.py", line 554
, in _prepare_file
require_hashes
File "C:\ProgramData\Anaconda2\lib\site-packages\pip\req\req_install.py", line
278, in populate_link
self.link = finder.find_requirement(self, upgrade)
File "C:\ProgramData\Anaconda2\lib\site-packages\pip\index.py", line 465, in f
ind_requirement
all_candidates = self.find_all_candidates(req.name)
File "C:\ProgramData\Anaconda2\lib\site-packages\pip\index.py", line 423, in f
ind_all_candidates
for page in self._get_pages(url_locations, project_name):
File "C:\ProgramData\Anaconda2\lib\site-packages\pip\index.py", line 568, in _
get_pages
page = self.get_page(location)
File "C:\ProgramData\Anaconda2\lib\site-packages\pip\index.py", line 683, in _
get_page
return HTMLPage.get_page(link, session=self.session)
File "C:\ProgramData\Anaconda2\lib\site-packages\pip\index.py", line 811, in g
et_page
inst = cls(resp.content, resp.url, resp.headers)
File "C:\ProgramData\Anaconda2\lib\site-packages\pip\index.py", line 731, in _
init
namespaceHTMLElements=False,
TypeError: parse() got an unexpected keyword argument 'transport_encoding'
```

I don't know what to do. It's package is very important for me because I need it to migrate from MATLAB.
I am using Windows platform, Windows 7.

**Comment by stsievert** [comment]
This package is not on the conda package manager and is instead on PyPI. Try running

    pip install drawnow

These install instructions are detailed in the readme.

**Comment by sripetta** [comment]
You can see in my post that I had tried "pip install drawnow" and it not worked.

```
pip install drawnow

Exception:
Traceback (most recent call last):
File "C:\ProgramData\Anaconda2\lib\site-packages\pip\basecommand.py", line 215
, in main
status = self.run(options, args)
File "C:\ProgramData\Anaconda2\lib\site-packages\pip\commands\install.py", lin
e 335, in run
wb.build(autobuilding=True)
File "C:\ProgramData\Anaconda2\lib\site-packages\pip\wheel.py", line 749, in b
uild
self.requirement_set.prepare_files(self.finder)
File "C:\ProgramData\Anaconda2\lib\site-packages\pip\req\req_set.py", line 380
, in prepare_files
ignore_dependencies=self.ignore_dependencies))
File "C:\ProgramData\Anaconda2\lib\site-packages\pip\req\req_set.py", line 554
, in _prepare_file
require_hashes
File "C:\ProgramData\Anaconda2\lib\site-packages\pip\req\req_install.py", line
278, in populate_link
self.link = finder.find_requirement(self, upgrade)
File "C:\ProgramData\Anaconda2\lib\site-packages\pip\index.py", line 465, in f
ind_requirement
all_candidates = self.find_all_candidates(req.name)
File "C:\ProgramData\Anaconda2\lib\site-packages\pip\index.py", line 423, in f
ind_all_candidates
for page in self._get_pages(url_locations, project_name):
File "C:\ProgramData\Anaconda2\lib\site-packages\pip\index.py", line 568, in _
get_pages
page = self.get_page(location)
File "C:\ProgramData\Anaconda2\lib\site-packages\pip\index.py", line 683, in _
get_page
return HTMLPage.get_page(link, session=self.session)
File "C:\ProgramData\Anaconda2\lib\site-packages\pip\index.py", line 811, in g
et_page
inst = cls(resp.content, resp.url, resp.headers)
File "C:\ProgramData\Anaconda2\lib\site-packages\pip\index.py", line 731, in _
init
namespaceHTMLElements=False,
TypeError: parse() got an unexpected keyword argument 'transport_encoding'
```

**Comment by stsievert** [comment]
Looks like you have an out of date html5lib. Try running

```
pip install html5lib==1.0b10
```

Then `pip install drawnow` should work.

This is similar to https://github.com/Kozea/WeasyPrint/issues/353. A quick search pulled it up.

**Comment by jojonki** [comment]
I also faced this problem while installing other libraries. Here is a my solution to install html5lib to avoid `transport_encoding` problem. I installed it from source because my pip didn't work by itself. So I needed to avoid `pip`.

- Windows 10
- python 3.6.2, Anaconda

```
pip uninstall html5lib  // risky, you cannot use pip until you can install html5lib
// download html5lib src from https://pypi.python.org/pypi/html5lib#downloads
tar zxvf html5lib-0.999999999.tar.gz
cd html5lib-0.999999999
python setup.py build
python setup.py install
```

Then, I hope you can install other libraries.

**Comment by sripetta** [comment]
jojonki, thank you for your answer but the problem is that I am working in a Windows platform and your solution is for linux platform.
I don't like windows but for some job's reasons I have to use this.

**Comment by jojonki** [comment]
@sripetta My environment is defenitely Windows 10.

**Comment by stsievert** [comment]
@jojonki how were you running those commands? via the windows command prompt?

**Comment by jojonki** [comment]
@stsievert I used `cmder` terminal. If you mentioned about `tar` command, you can unzip the file with many windows applications, like `7-zip`.

**Comment by sripetta** [comment]
Sorry for my delay.
I tried the jojonki solution, but I still have the problem.
I used the conda console. You can see the output bellow:
 
```
(C:\ProgramData\Anaconda2) C:\Users\Downloads\html5lib-0.999999
999\html5lib-0.999999999>pip uninstall html5lib
DEPRECATION: Uninstalling a distutils installed project (html5lib) has been depr
ecated and will be removed in a future version. This is due to the fact that uni
nstalling a distutils project will only partially uninstall the project.
Uninstalling html5lib-0.999:
  c:\programdata\anaconda2\lib\site-packages\html5lib-0.999-py2.7.egg-info
Proceed (y/n)? y
  Successfully uninstalled html5lib-0.999

(C:\ProgramData\Anaconda2) C:\Users\Downloads\html5lib-0.999999
999\html5lib-0.999999999>python setup.py build
running build
running build_py

(C:\ProgramData\Anaconda2) C:\Users\Downloads\html5lib-0.999999
999\html5lib-0.999999999>python setup.py install
running install
running bdist_egg
running egg_info
writing requirements to html5lib.egg-info\requires.txt
writing html5lib.egg-info\PKG-INFO
writing top-level names to html5lib.egg-info\top_level.txt
writing dependency_links to html5lib.egg-info\dependency_links.txt
reading manifest file 'html5lib.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'html5lib.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
creating build\bdist.win-amd64
creating build\bdist.win-amd64\egg
creating build\bdist.win-amd64\egg\html5lib
copying build\lib\html5lib\constants.py -> build\bdist.win-amd64\egg\html5lib
creating build\bdist.win-amd64\egg\html5lib\filters
copying build\lib\html5lib\filters\alphabeticalattributes.py -> build\bdist.win-
amd64\egg\html5lib\filters
copying build\lib\html5lib\filters\base.py -> build\bdist.win-amd64\egg\html5lib
\filters
copying build\lib\html5lib\filters\inject_meta_charset.py -> build\bdist.win-amd
64\egg\html5lib\filters
copying build\lib\html5lib\filters\lint.py -> build\bdist.win-amd64\egg\html5lib
\filters
copying build\lib\html5lib\filters\optionaltags.py -> build\bdist.win-amd64\egg\
html5lib\filters
copying build\lib\html5lib\filters\sanitizer.py -> build\bdist.win-amd64\egg\htm
l5lib\filters
copying build\lib\html5lib\filters\whitespace.py -> build\bdist.win-amd64\egg\ht
ml5lib\filters
copying build\lib\html5lib\filters\__init__.py -> build\bdist.win-amd64\egg\html
5lib\filters
copying build\lib\html5lib\html5parser.py -> build\bdist.win-amd64\egg\html5lib
copying build\lib\html5lib\serializer.py -> build\bdist.win-amd64\egg\html5lib
creating build\bdist.win-amd64\egg\html5lib\treeadapters
copying build\lib\html5lib\treeadapters\genshi.py -> build\bdist.win-amd64\egg\h
tml5lib\treeadapters
copying build\lib\html5lib\treeadapters\sax.py -> build\bdist.win-amd64\egg\html
5lib\treeadapters
copying build\lib\html5lib\treeadapters\__init__.py -> build\bdist.win-amd64\egg
\html5lib\treeadapters
creating build\bdist.win-amd64\egg\html5lib\treebuilders
copying build\lib\html5lib\treebuilders\base.py -> build\bdist.win-amd64\egg\htm
l5lib\treebuilders
copying build\lib\html5lib\treebuilders\dom.py -> build\bdist.win-amd64\egg\html
5lib\treebuilders
copying build\lib\html5lib\treebuilders\etree.py -> build\bdist.win-amd64\egg\ht
ml5lib\treebuilders
copying build\lib\html5lib\treebuilders\etree_lxml.py -> build\bdist.win-amd64\e
gg\html5lib\treebuilders
copying build\lib\html5lib\treebuilders\__init__.py -> build\bdist.win-amd64\egg
\html5lib\treebuilders
creating build\bdist.win-amd64\egg\html5lib\treewalkers
copying build\lib\html5lib\treewalkers\base.py -> build\bdist.win-amd64\egg\html
5lib\treewalkers
copying build\lib\html5lib\treewalkers\dom.py -> build\bdist.win-amd64\egg\html5
lib\treewalkers
copying build\lib\html5lib\treewalkers\etree.py -> build\bdist.win-amd64\egg\htm
l5lib\treewalkers
copying build\lib\html5lib\treewalkers\etree_lxml.py -> build\bdist.win-amd64\eg
g\html5lib\treewalkers
copying build\lib\html5lib\treewalkers\genshi.py -> build\bdist.win-amd64\egg\ht
ml5lib\treewalkers
copying build\lib\html5lib\treewalkers\__init__.py -> build\bdist.win-amd64\egg\
html5lib\treewalkers
copying build\lib\html5lib\_ihatexml.py -> build\bdist.win-amd64\egg\html5lib
copying build\lib\html5lib\_inputstream.py -> build\bdist.win-amd64\egg\html5lib

copying build\lib\html5lib\_tokenizer.py -> build\bdist.win-amd64\egg\html5lib
creating build\bdist.win-amd64\egg\html5lib\_trie
copying build\lib\html5lib\_trie\datrie.py -> build\bdist.win-amd64\egg\html5lib
\_trie
copying build\lib\html5lib\_trie\py.py -> build\bdist.win-amd64\egg\html5lib\_tr
ie
copying build\lib\html5lib\_trie\_base.py -> build\bdist.win-amd64\egg\html5lib\
_trie
copying build\lib\html5lib\_trie\__init__.py -> build\bdist.win-amd64\egg\html5l
ib\_trie
copying build\lib\html5lib\_utils.py -> build\bdist.win-amd64\egg\html5lib
copying build\lib\html5lib\__init__.py -> build\bdist.win-amd64\egg\html5lib
byte-compiling build\bdist.win-amd64\egg\html5lib\constants.py to constants.pyc
byte-compiling build\bdist.win-amd64\egg\html5lib\filters\alphabeticalattributes
.py to alphabeticalattributes.pyc
byte-compiling build\bdist.win-amd64\egg\html5lib\filters\base.py to base.pyc
byte-compiling build\bdist.win-amd64\egg\html5lib\filters\inject_meta_charset.py
 to inject_meta_charset.pyc
byte-compiling build\bdist.win-amd64\egg\html5lib\filters\lint.py to lint.pyc
byte-compiling build\bdist.win-amd64\egg\html5lib\filters\optionaltags.py to opt
ionaltags.pyc
byte-compiling build\bdist.win-amd64\egg\html5lib\filters\sanitizer.py to saniti
zer.pyc
byte-compiling build\bdist.win-amd64\egg\html5lib\filters\whitespace.py to white
space.pyc
byte-compiling build\bdist.win-amd64\egg\html5lib\filters\__init__.py to __init_
_.pyc
byte-compiling build\bdist.win-amd64\egg\html5lib\html5parser.py to html5parser.
pyc
byte-compiling build\bdist.win-amd64\egg\html5lib\serializer.py to serializer.py
c
byte-compiling build\bdist.win-amd64\egg\html5lib\treeadapters\genshi.py to gens
hi.pyc
byte-compiling build\bdist.win-amd64\egg\html5lib\treeadapters\sax.py to sax.pyc

byte-compiling build\bdist.win-amd64\egg\html5lib\treeadapters\__init__.py to __
init__.pyc
byte-compiling build\bdist.win-amd64\egg\html5lib\treebuilders\base.py to base.p
yc
byte-compiling build\bdist.win-amd64\egg\html5lib\treebuilders\dom.py to dom.pyc

byte-compiling build\bdist.win-amd64\egg\html5lib\treebuilders\etree.py to etree
.pyc
byte-compiling build\bdist.win-amd64\egg\html5lib\treebuilders\etree_lxml.py to
etree_lxml.pyc
byte-compiling build\bdist.win-amd64\egg\html5lib\treebuilders\__init__.py to __
init__.pyc
byte-compiling build\bdist.win-amd64\egg\html5lib\treewalkers\base.py to base.py
c
byte-compiling build\bdist.win-amd64\egg\html5lib\treewalkers\dom.py to dom.pyc
byte-compiling build\bdist.win-amd64\egg\html5lib\treewalkers\etree.py to etree.
pyc
byte-compiling build\bdist.win-amd64\egg\html5lib\treewalkers\etree_lxml.py to e
tree_lxml.pyc
byte-compiling build\bdist.win-amd64\egg\html5lib\treewalkers\genshi.py to gensh
i.pyc
byte-compiling build\bdist.win-amd64\egg\html5lib\treewalkers\__init__.py to __i
nit__.pyc
byte-compiling build\bdist.win-amd64\egg\html5lib\_ihatexml.py to _ihatexml.pyc
byte-compiling build\bdist.win-amd64\egg\html5lib\_inputstream.py to _inputstrea
m.pyc
byte-compiling build\bdist.win-amd64\egg\html5lib\_tokenizer.py to _tokenizer.py
c
byte-compiling build\bdist.win-amd64\egg\html5lib\_trie\datrie.py to datrie.pyc
byte-compiling build\bdist.win-amd64\egg\html5lib\_trie\py.py to py.pyc
byte-compiling build\bdist.win-amd64\egg\html5lib\_trie\_base.py to _base.pyc
byte-compiling build\bdist.win-amd64\egg\html5lib\_trie\__init__.py to __init__.
pyc
byte-compiling build\bdist.win-amd64\egg\html5lib\_utils.py to _utils.pyc
byte-compiling build\bdist.win-amd64\egg\html5lib\__init__.py to __init__.pyc
creating build\bdist.win-amd64\egg\EGG-INFO
copying html5lib.egg-info\PKG-INFO -> build\bdist.win-amd64\egg\EGG-INFO
copying html5lib.egg-info\SOURCES.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying html5lib.egg-info\dependency_links.txt -> build\bdist.win-amd64\egg\EGG-
INFO
copying html5lib.egg-info\requires.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying html5lib.egg-info\top_level.txt -> build\bdist.win-amd64\egg\EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating dist
creating 'dist\html5lib-0.999999999-py2.7.egg' and adding 'build\bdist.win-amd64
\egg' to it
removing 'build\bdist.win-amd64\egg' (and everything under it)
Processing html5lib-0.999999999-py2.7.egg
Copying html5lib-0.999999999-py2.7.egg to c:\programdata\anaconda2\lib\site-pack
ages
Adding html5lib 0.999999999 to easy-install.pth file

Installed c:\programdata\anaconda2\lib\site-packages\html5lib-0.999999999-py2.7.
egg
Processing dependencies for html5lib==0.999999999
Searching for setuptools==27.2.0
Best match: setuptools 27.2.0
Processing setuptools-27.2.0-py2.7.egg
Adding setuptools 27.2.0 to easy-install.pth file
Installing easy_install-script.py script to C:\ProgramData\Anaconda2\Scripts
Installing easy_install.exe script to C:\ProgramData\Anaconda2\Scripts
Installing easy_install-2.7-script.py script to C:\ProgramData\Anaconda2\Scripts

Installing easy_install-2.7.exe script to C:\ProgramData\Anaconda2\Scripts

Using c:\programdata\anaconda2\lib\site-packages\setuptools-27.2.0-py2.7.egg
Searching for webencodings==0.5.1
Best match: webencodings 0.5.1
Adding webencodings 0.5.1 to easy-install.pth file

Using c:\programdata\anaconda2\lib\site-packages
Searching for six==1.10.0
Best match: six 1.10.0
Adding six 1.10.0 to easy-install.pth file

Using c:\programdata\anaconda2\lib\site-packages
Finished processing dependencies for html5lib==0.999999999

(C:\ProgramData\Anaconda2) C:\Users\Downloads\html5lib-0.999999
999\html5lib-0.999999999>pip install drawnow
Collecting drawnow
Exception:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda2\lib\site-packages\pip\basecommand.py", line 215
, in main
    status = self.run(options, args)
  File "C:\ProgramData\Anaconda2\lib\site-packages\pip\commands\install.py", lin
e 335, in run
    wb.build(autobuilding=True)
  File "C:\ProgramData\Anaconda2\lib\site-packages\pip\wheel.py", line 749, in b
uild
    self.requirement_set.prepare_files(self.finder)
  File "C:\ProgramData\Anaconda2\lib\site-packages\pip\req\req_set.py", line 380
, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "C:\ProgramData\Anaconda2\lib\site-packages\pip\req\req_set.py", line 554
, in _prepare_file
    require_hashes
  File "C:\ProgramData\Anaconda2\lib\site-packages\pip\req\req_install.py", line
 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "C:\ProgramData\Anaconda2\lib\site-packages\pip\index.py", line 465, in f
ind_requirement
    all_candidates = self.find_all_candidates(req.name)
  File "C:\ProgramData\Anaconda2\lib\site-packages\pip\index.py", line 423, in f
ind_all_candidates
    for page in self._get_pages(url_locations, project_name):
  File "C:\ProgramData\Anaconda2\lib\site-packages\pip\index.py", line 568, in _
get_pages
    page = self._get_page(location)
  File "C:\ProgramData\Anaconda2\lib\site-packages\pip\index.py", line 683, in _
get_page
    return HTMLPage.get_page(link, session=self.session)
  File "C:\ProgramData\Anaconda2\lib\site-packages\pip\index.py", line 792, in g
et_page
    "Cache-Control": "max-age=600",
  File "C:\ProgramData\Anaconda2\lib\site-packages\requests\sessions.py", line 5
31, in get
    return self.request('GET', url, **kwargs)
  File "C:\ProgramData\Anaconda2\lib\site-packages\pip\download.py", line 386, i
n request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "C:\ProgramData\Anaconda2\lib\site-packages\requests\sessions.py", line 5
18, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\ProgramData\Anaconda2\lib\site-packages\requests\sessions.py", line 6
39, in send
    r = adapter.send(request, **kwargs)
  File "C:\ProgramData\Anaconda2\lib\site-packages\cachecontrol\adapter.py", lin
e 50, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "C:\ProgramData\Anaconda2\lib\site-packages\requests\adapters.py", line 4
38, in send
    timeout=timeout
  File "C:\ProgramData\Anaconda2\lib\site-packages\requests\packages\urllib3\con
nectionpool.py", line 649, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\ProgramData\Anaconda2\lib\site-packages\requests\packages\urllib3\uti
l\retry.py", line 337, in increment
    total -= 1
TypeError: unsupported operand type(s) for -=: 'Retry' and 'int'

(C:\ProgramData\Anaconda2) C:\Users\Downloads\html5lib-0.999999
999\html5lib-0.999999999>
```

**Comment by stsievert** [comment]
Thanks for sticking and running these commands – package install in Python is not normally this difficult!

Does installing other `pip` packages give you the same error? For example, try `pip install requests` and `pip install flask`. If these don't work I would re-install Anaconda (or file issues on their issue trackers).

**Comment by nobb26** [comment]
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.
I am trying to also install drawnow via pip. I keep getting this comment, I am a raw beginner hobbyist and brand new to github. I assume bottom three lines is reason for non installation.
 Can anyone advise please?

C:\Users\austen>pip install drawnow
Collecting drawnow
Collecting matplotlib>=1.5 (from drawnow)
  Using cached https://files.pythonhosted.org/packages/6e/39/dbb652fc52382c8d88d
47e5195f0bb7f8d5216a502630db0f8134f4a6dab/matplotlib-2.2.2-cp27-cp27m-win32.whl
Requirement already satisfied: kiwisolver>=1.0.1 in c:\python27\lib\site-package
s (from matplotlib>=1.5->drawnow) (1.0.1)
Requirement already satisfied: numpy>=1.7.1 in c:\python27\lib\site-packages (fr
om matplotlib>=1.5->drawnow) (1.9.1)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in c:\py
thon27\lib\site-packages (from matplotlib>=1.5->drawnow) (2.2.0)
Requirement already satisfied: backports.functools-lru-cache in c:\python27\lib\
site-packages (from matplotlib>=1.5->drawnow) (1.5)
Requirement already satisfied: six>=1.10 in c:\python27\lib\site-packages (from
matplotlib>=1.5->drawnow) (1.11.0)
Requirement already satisfied: pytz in c:\python27\lib\site-packages (from matpl
otlib>=1.5->drawnow) (2018.4)
Requirement already satisfied: cycler>=0.10 in c:\python27\lib\site-packages (fr
om matplotlib>=1.5->drawnow) (0.10.0)
Requirement already satisfied: python-dateutil>=2.1 in c:\python27\lib\site-pack
ages (from matplotlib>=1.5->drawnow) (2.7.3)
Requirement already satisfied: setuptools in c:\python27\lib\site-packages (from
 kiwisolver>=1.0.1->matplotlib>=1.5->drawnow) (28.8.0)
Installing collected packages: matplotlib, drawnow
  Found existing installation: matplotlib 1.2.0
Cannot uninstall 'matplotlib'. It is a distutils installed project and thus we c
annot accurately determine which files belong to it which would lead to only a p
artial uninstall.

C:\Users\austen>

**Comment by stsievert** [comment]
It looks like you’re running into a version conflict. draw now requires matplotlib>=v1.5 and you have v1.2. pip can’t accurately uninstall matplotlib because of some complications on how it was installed. Did you install matplotlib by downloading it and running “python setup.py install”?

I think it’s work to “conda update matplotlib” should do the trick if you’re on Anaconda.

**Comment by nobb26** [comment]
Scott
Thank you for your response.
I have been following a series of YouTube tutorials run by Paul McWhorter
"Arduino with Python" - Lesson 7 in this instance,
I am using Windows 7
So I installed Python 2.7.12
To install Matplotlib , following Paul McWhorter's instruction, I clicked
on the download for

matplotlib -1.2.0 win32-py2.7.exe

Maybe at the time  this YoutTube video was made you could download drawnow
via that version as he was ultimately able to import drawnow whereas I
couldn't..

Any  comment would be much appreciated.

Regards
Neil Austen

**Comment by stsievert** [comment]
Why did you download matplotlib v1.2.0 in particular and not the most recent version? Why did you download through your web browser instead of using `pip` or `conda`? His video looks pretty old, posted sometime in 2014.

(I'd also recommend Python 3 instead of Python 2)

**Comment by nobb26** [comment]
Thanks Scott
I guess it was my mistake following a YouTube tutorial that was out of date. Anyway I appreciate your showing me why I couldn’t download drawnow from old version of maplotlib.
Best Wishes
Neil Austen

**Comment by stsievert** [comment]
No worries on following YouTube videos – I've done similar things. But I'd try to install the more recent versions of various packages for issues like this.

The way I would install drawnow (or almost any package) is with `pip install drawnow` or `conda install drawnow`, not a direct download through a web browser.
